#!/bin/sh
[ -z "$1" ] && echo project name needed 2>&1 && exit 1
dir=~/src/$1
[ -d "$dir" ] || mkdir $dir
cd $dir

git init >&2
git checkout -b master >&2

touch "$1.js" "README.md"

git remote add origin https://archive.voodoowarez.com/"$1" >&2
git remote add github git@github.com:rektide/"$1" >&2
git config branch.master.remote github
git config branch.master.merge refs/heads/master
#git config branch.master.rebase true

npm init -y >&2

# set the good stuff
jq "$(cat <<EOF
. + {
	author: "${AUTHOR-$(git config --get user.name)}",
	license: "${LICENSE-MIT}",
	main: "index.js",
	module: "$1.js",
	esm: true,
	"@std/esm": {
		cjs: {
			namedExports: true
		}
	}
}
EOF
)" package.json | unexpand -t 2 - > package.json.tmp
mv package.json.tmp package.json
cat package.json
